### ISSUE TITLE
report

### ISSUE THREAD

**Issue by DimonYoing** [Lycol50/Valentines#1]
please add a discord bot to the reportsystem, when you send a report to a player, it is automatically transferred to the discord group

**Comment by DimonYoing** [comment]
Just please no virion

**Comment by Lycol50** [comment]
@DimonYoing
Thank you for taking interest on another repository [ReportSystem](https://github.com/PinakaMalupetnaServer/ReportSystem) , unfortunately we already ended the support for PMnS plugins, like this one, and i have decided to not upgrade it to API4, and abandon this anymore.

If you need more something, please email me at **frizth_tatierra@informatics.edu.ph**
